define({
    homeLinkText: "Home",
    addSiteLinkText: "Add Site",
    appTitle: "KnowledgeLake Search Mobile",
    configureSitePageTitle: "Configure Site",
    savedSearchesPageTitle: "Saved Searches",
    searchBuilderPageTitle: "Search Builder",
    resultsPageTitle: "Search Results",
    documentPageTitle: "Document",
    localSavedSearches: "Local Saved Searches",
    serverSavedSearches: "Server Saved Searches",
    cancel: "Cancel",
    save: "Save",
    addSite: "Add",
    editSite: "Edit",
    editProperties: "Edit",
	viewProperties: "View",
    deleteSite: "Delete",
	search: "Search",
    download: "Download",
    siteUrl: "Url",
    siteTitle: "Title",
    validate: "Validate",
	keywordsWatermark: "Keywords",
    loading: "Loading...",
    searching: "Searching...",
    credentialType: "Type",
    windowsCredentials: "Windows Credentials",
    userName: "User",
    password: "Password",
    domain: "Domain",
    windows: "Windows",
    claimsForms: "Claims/Forms",
	saveSuccess: "Site saved successfully!",
    urlValidMessage: "The URL is valid",
    urlInvalidMessage: "The URL is not valid",
    credentialsInvalidMessage: "The site credentials are not valid",
    logonFailed: "Logon to SharePoint failed",
    logonSuccess: "Logon to SharePoint succeeded",
	unauthorized: "Unauthorized",
    siteAlreadyConfigured: "Site has already been added",
	siteLoadError: "Error loading saved sites",
    errorWritingSiteData: "Error saving site data to the file system",
    siteTitleRequired: "Site title is required",
	resultCountFormat: "Search Returned {0} Results",
	noResultsFound: "No Results Found",
	searching: "Searching...",
	back: "Back",
	protocol: "Protocol",
	urlPlaceholder: "www.server.com",
	siteTitlePlaceholder: "Enter a title...",
	userNamePlaceholder: "Domain\\User Name",
	passwordPlaceholder: "Password",
    searchError: "An error occured while performing your search",
	showPassword: "Show Password",
    Range: "Range",
    Contains: "Contains",
    StartsWith: "Starts With",
    Like: "Like",
    IsNotNull: "Is Not Null",
    Yes: "Yes",
    No: "No",
    NotSet: "Not Set",
	DeleteSiteSuccess: "Site deleted",
	DeleteSiteFailed: "Failed to delete site",
	SiteDataEmpty: "Site data has not been populated",
	SiteConnectionExists: "Site connection already exists.",
	InvalidSite: "Site connection does not exist.",
	LoadFileSysystemFailure: "Unable to connect to the file system",	
	FileSystemNull: "File system is not initialized.",
	FileFound: "File found.",
	FileNotFound: "File not found.",
	FileReadFailure: "Failed to read data from file.",
	FileWriteSuccess: "File write successful.",
	FileWriteFailure: "Failed to write data to file.",       
	FileDeleteSuccess: "File delete successful.",       
	FileDeleteFailure: "Failed to delete file.",
	GetWriterFailure: "Failed to create file writer.",
	GetFileFailure: "Failed to get file entry.",
	GetFileInstanceFailure: "Failed to get file instance.",	
	CreateFileFailure: "Unable to create file.",
	CreateDirectoryFailure: "Unable to create file directory.",
	AccessDirectoryFailure: "Unable to access file directory.",	
	LogonSucceeded: "Logon succeeded.",
	And: "And",
	Or: "Or"
});