define({
    homeLinkText: "Home",
    addSiteLinkText: "Add Site",
    appTitle: "KnowledgeLake Search Mobile",
    configureSitePageTitle: "Configure Site",
    savedSearchesPageTitle: "Saved Searches",
    searchBuilderPageTitle: "Search Builder",
    resultsPageTitle: "Search Results",
    documentPageTitle: "Document",
    localSavedSearches: "Local Saved Searches",
    serverSavedSearches: "Server Saved Searches",
    cancel: "Cancel",
    save: "Save",
    addSite: "Add",
    editSite: "Edit",
    editProperties: "Edit",
    deleteSite: "Delete",
	search: "Search",
    download: "Download",
    siteUrl: "Url",
    siteTitle: "Title",
    validate: "Validate",
	keywordsWatermark: "Keywords",
    loading: "Loading...",
    searching: "Searching...",
    credentialType: "Type",
    windowsCredentials: "Windows Credentials",
    userName: "User",
    password: "Password",
    domain: "Domain",
    windows: "Windows",
    claimsForms: "Claims/Forms",
	saveSuccess: "Site saved successfully!",
    urlValidMessage: "The URL is valid",
    urlInvalidMessage: "The URL is not valid",
    credentialsInvalidMessage: "The site credentials are not valid",
    logonFailed: "Logon to SharePoint failed",
    logonSuccess: "Logon to SharePoint succeeded",
	unauthorized: "Unauthorized",
    siteAlreadyConfigured: "Site has already been added",
    errorWritingSiteData: "Error saving site data to the file system",
    siteTitleRequired: "Site title is required",
	resultCountFormat: "Search Returned {0} Results",
	noResultsFound: "No Results Found",
	searching: "Searching...",
	back: "Back",
	protocol: "Protocol",
	urlPlaceholder: "www.server.com",
	siteTitlePlaceholder: "Enter a title...",
	userNamePlaceholder: "Domain\\User Name",
	passwordPlaceholder: "Password",
    searchError: "An error occured while performing your search",
	showPassword: "Show Password",
    Range: "Range",
    Contains: "Contains",
    StartsWith: "Starts With",
    Like: "Like",
    IsNotNull: "Is Not Null",
    Yes: "Yes",
    No: "No",
    NotSet: "Not Set",
	SiteDataEmpty: "Site data has not been populated",
	SiteConnectionExists: "Site connection already exists.",
	InvalidSite: "Site connection does not exist."
});