define({
    homeLinkText: "Home",
    addSiteLinkText: "Add Site",
    appTitle: "KnowledgeLake Search Mobile",
    configureSitePageTitle: "Configure Site",
    searchPageTitle: "Search",
    searchBuilderPageTitle: "Search Builder",
    resultsPageTitle: "Search Results",
    documentPageTitle: "Document",
    cancel: "Cancel",
    save: "Save",
    addSite: "Add",
    editSite: "Edit",
    editProperties: "Edit",
    deleteSite: "Delete",
	search: "Search",
    download: "Download",
    siteUrl: "Url",
    siteTitle: "Title",
    validate: "Validate",
	keywordsWatermark: "Keywords",
    loading: "Loading...",
    searching: "Searching...",
    credentialType: "Type",
    windowsCredentials: "Windows Credentials",
    userName: "User",
    password: "Password",
    domain: "Domain",
    windows: "Windows",
    claimsForms: "Claims/Forms",
    urlValidMessage: "The URL is valid",
    urlInvalidMessage: "The URL is not valid",
    credentialsInvalidMessage: "The site credentials are not valid",
    logonFailed: "Logon to SharePoint failed",
    logonSuccess: "Logon to SharePoint succeeded",
	unauthorized: "Unauthorized",
    siteAlreadyConfigured: "Site has already been added",
    errorWritingSiteData: "Error saving site data to the file system",
    siteTitleRequired: "Site title is required",
	noResultsFound: "No results found...",
	searching: "Searching...",
	back: "Back"
});